### ISSUE TITLE
Make Daily sales bar graph "clickable"

### ISSUE THREAD

**Issue by dankiefer** [K3S/K3S-Replenish-Black-Bean#420]
Would be very cool if the bars on the daily sales history screen were clickable.  When clicked, it would open up a separate tab or window that would be our "daily sales" screen to show which customers bought what quantity.

<img width="1011" alt="screen shot 2016-12-28 at 10 17 18 am" src="https://cloud.githubusercontent.com/assets/19612381/21524860/4f78f848-cce7-11e6-8cab-280989761328.png">

**Comment by kingharrison** [comment]
This issue was moved to K3S/New-Ideas#3
