### ISSUE TITLE
Sales vs Inventory vs Service level graph

### ISSUE THREAD

**Issue by dankiefer** [K3S/K3S-Replenish-Black-Bean#421]
<img width="1029" alt="screen shot 2016-12-28 at 9 59 51 am" src="https://cloud.githubusercontent.com/assets/19612381/21524923/a066ca14-cce7-11e6-9163-2619dc1ae0a4.png">
I created this from Myers-Cox data and realized it would be a fantastic graph for Blackbean.  This shows the average weekly inventory and the weekly sales for their daily replenishment products.  We also discussed overlaying a service level graph as well.

**Comment by kingharrison** [comment]
This issue was moved to K3S/New-Ideas#4
