### ISSUE TITLE
Hi-light periods that have created PE Checks

### ISSUE THREAD

**Issue by dankiefer** [K3S/K3S-Replenish-Black-Bean#427]
On the history screen, show periods that had pe checks in a different color, or bold, italics...something.
![screen shot 2017-01-14 at 8 29 16 am](https://cloud.githubusercontent.com/assets/19612381/21955246/cfeaf12a-da34-11e6-8f85-85af9cc2fb3f.png)

**Comment by kingharrison** [comment]
This issue was moved to K3S/New-Ideas#6
