### ISSUE TITLE
Make historical data clickable

### ISSUE THREAD

**Issue by dankiefer** [K3S/K3S-Replenish-Black-Bean#429]
Same idea as for daily replenishment. Could we allow them to click on the period demand to filter the daily sales for that product?
![screen shot 2017-01-14 at 8 29 16 am](https://cloud.githubusercontent.com/assets/19612381/21955263/65c522e2-da35-11e6-806b-03b3fc49fba9.png)

**Comment by kingharrison** [comment]
This issue was moved to K3S/New-Ideas#7
